fix: replace macros with inline funtction
Fix clang-format error with macros, we should avoid statement in macro.

./script/clang-format.sh -n
Formatting [1/2] app/src/main/jni/librime_jni/jni-utils.h
Formatting [2/2] app/src/main/jni/librime_jni/objconv.h
Formatting [1/4] app/src/main/jni/librime_jni/key_table.cc
Formatting [2/4] app/src/main/jni/librime_jni/levers.cc
Formatting [3/4] app/src/main/jni/librime_jni/opencc.cc
Formatting [4/4] app/src/main/jni/librime_jni/rime_jni.cc
app/src/main/jni/librime_jni/rime_jni.cc:141:55: error: code should be clang-formatted [-Wclang-format-violations]
#define RETURN_IF_NOT_RUNNING DO_IF_NOT_RUNNING(return)
                                                      ^
Replace macros with inline funtction, since it's fast and more maintainable.

Reference: https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html